#!/usr/bin/env sh

limelight -m config width 2
limelight -m config radius 10
limelight -m config placement exterior

# Color: AARRGGBB
limelight -m config active_color 0xFFBF40BF
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
